name: CI с SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  sonarcloud-scan:
    name: Запуск тестов и SonarCloud анализа
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -e .

      - name: Запуск тестов с покрытием
        run: |
          pytest --cov=gendiff --cov-report=xml tests/

      - name: Анализ SonarCloud
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=ваш_ключ_проекта
            -Dsonar.organization=ваша_организация
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=gendiff
            -Dsonar.tests=tests
